spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://34.64.245.142:3306/MovieDBTest
    username: test
    password: sistloltest12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:movieReservation;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true