spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mrs
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

api:
  kobis:
    key: 00becfd165e8d638edf8c2e79d45cfac
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/
  naver:
    ClientID: w7GZy982xWYks5kMMn1x
    ClientSecret: dQfsJMgD7f
    url: https://openapi.naver.com/v1/search/movie.json

